server:
  port: 8080

spring:
  application:
    name: weather-traffic-alarm-backend

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
      show-details: when-authorized
    info:
      enabled: true
