import { EVALUATION_FIXTURE_STATES, REPEAT_KINDS, createEvaluationFixture, repeatLabel } from './state.mjs';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const weekday = ['一','二','三','四','五','六','日'];

export function createAlarmScreens({ action, overlayAction, asset, state }) {
  const read = () => (typeof state === 'function' ? state() : state) || {};
  const link = (label, route, extra = '') => action(label, route, extra);
  const event = (label, name, value = '') => overlayAction(label, name, value);
  const icon = (file, alt = '') => asset(file, alt, 'alarm-icon');
  const current = () => { const snapshot = read(); const c = snapshot.config || snapshot; const r = snapshot.runtime || {}; return { c, r, plan:r.alarmDraft || c.alarmPlans?.find(item => item.id === r.editingAlarmId) }; };
  const assessment = () => { const { r } = current(); return r.evaluationRun || createEvaluationFixture({ fixture:r.evaluationFixture || EVALUATION_FIXTURE_STATES.PENDING, plan:r.evaluationPlan }); };
  const footer = content => `<footer class="screen-footer alarm-footer">${content}</footer>`;
  const status = plan => ({ pendingPermission:'待 Android 注册', registered:'已注册', failed:'注册失败', completed:'已完成' })[plan.scheduleStatus] || '待 Android 注册';
  return {
    plans() {
      const { c } = current(); const plans = c.alarmPlans || [];
      const card = plan => `<article class="local-alarm-card ${plan.enabled ? '' : 'is-disabled'}"><header><button type="button" data-action="edit-alarm" data-value="${esc(plan.id)}"><b>${esc(plan.name)}</b><small>${esc(repeatLabel(plan))}</small></button><label class="alarm-switch"><input type="checkbox" data-action="toggle-alarm" data-value="${esc(plan.id)}" ${plan.enabled ? 'checked' : ''}><span></span></label></header><div><b>${esc(plan.time)}</b><p>${esc(status(plan))}<small>${plan.enabled ? '由 Android 本地闹钟服务处理' : '已停用'}</small></p></div><footer><span>${plan.vibration ? '振动开启' : '振动关闭'} · 贪睡 ${plan.snoozeMinutes} 分钟</span>${event('编辑','edit-alarm',plan.id)}</footer></article>`;
      return `<section class="alarm-page alarm-plans"><p class="alarm-page-note">高德通勤支持全局设置与计划覆盖。</p>${plans.length ? plans.map(card).join('') : `<article class="local-empty-state">${icon('2c52264e-dee6-4069-95c5-e8105043da04.svg')}<h2>还没有闹钟</h2><p>添加单次、每周或工作日闹钟。Android 将负责实际注册与响铃。</p></article>`}<button type="button" class="local-add-alarm" data-action="new-alarm">＋ 添加闹钟</button>${footer(link('查看本机记录','history','class="alarm-tonal-action"'))}</section>`;
    },
    'plan-edit'() {
      const { plan } = current(); if (!plan) return '<section class="alarm-page"><p>请选择一个闹钟。</p></section>';
      const repeat = plan.repeat || { kind:REPEAT_KINDS.ONCE }; const labels = { once:'指定日期', weekly:'每周重复', workdays:'工作日' };
      return `<section class="alarm-page alarm-plan-edit local-alarm-editor"><article class="alarm-baseline-card"><div><small>闹钟名称</small><em>${esc(status(plan))}</em></div><input class="local-name-input" data-alarm-field="name" value="${esc(plan.name)}" maxlength="24" aria-label="闹钟名称"><b>${esc(plan.time)}</b>${event('编辑时间','overlay','alarm-time')}</article><article class="alarm-rule-list"><label class="local-field"><span>日期与时间</span><input type="date" data-alarm-field="date" value="${esc(repeat.date || '')}" ${repeat.kind === REPEAT_KINDS.ONCE ? '' : 'disabled'}><input type="time" data-alarm-field="time" value="${esc(plan.time)}"></label><div class="local-repeat-group">${Object.entries(labels).map(([key,label]) => `<button type="button" data-action="select-repeat" data-value="${key}" class="${repeat.kind === key ? 'is-selected' : ''}">${label}</button>`).join('')}</div>${repeat.kind === REPEAT_KINDS.WEEKLY ? `<div class="local-weekdays">${weekday.map((label,index) => `<button type="button" data-action="toggle-weekday" data-value="${index + 1}" class="${repeat.weekdays?.includes(index + 1) ? 'is-selected' : ''}">${label}</button>`).join('')}</div>` : ''}</article><article class="alarm-sound-list"><div class="alarm-row">${icon('1a089d58-bce2-4212-9ddf-707263a04ac1.svg')}<strong>铃声与振动</strong><span>${esc(plan.ringtone)} · ${plan.vibration ? '开启' : '关闭'}</span>${event('','overlay','alarm-sound')}</div><div class="alarm-row">${icon('129742a8-cb1d-4163-9258-71c82066766b.svg')}<strong>贪睡时长</strong><span>${plan.snoozeMinutes} 分钟</span>${event('','overlay','alarm-snooze')}</div><button type="button" class="alarm-row local-calendar-entry" data-action="open-calendar"><strong>单日覆盖</strong><span>仅本计划指定日期</span><i>›</i></button></article><article class="alarm-sound-list evaluation-plan-settings"><div class="alarm-row"><strong>期望到达时间</strong><span>${esc(plan.arrivalTime)}</span>${event('','overlay','arrival-time')}</div><div class="alarm-row"><strong>准备时间</strong><span>${plan.preparationMinutes} 分钟</span>${event('','overlay','preparation-minutes')}</div><div class="alarm-row"><strong>最多提前</strong><span>${plan.maxAdvanceMinutes} 分钟</span>${event('','overlay','max-advance-minutes')}</div></article><article class="alarm-sound-list amap-plan-commute"><div><strong>通勤路线</strong><span>${plan.commuteOverride?.enabled ? '本计划覆盖' : '使用全局通勤'}</span></div><button type="button" data-action="edit-plan-commute">编辑本计划覆盖</button>${plan.commuteOverride?.enabled ? '<button type="button" data-action="use-global-commute">恢复全局通勤</button>' : ''}</article><button type="button" class="local-delete" data-action="delete-alarm" data-value="${esc(plan.id)}">删除闹钟</button>${footer(event('保存闹钟','save-alarm'))}</section>`;
    },
    history() { const { c, r } = current(); const events = (c.alarmEvents || []).filter(item => r.historyFilter === 'all' || !r.historyFilter || item.type === r.historyFilter); const label = ({all:'全部',registered:'已注册',stopped:'已停止',snoozed:'已贪睡',failed:'异常'})[r.historyFilter || 'all']; const decisions = r.evaluationHistory || []; const decisionCard = item => `<article class="evaluation-history-card is-${esc(item.state)}"><header><b>${esc(item.title)}</b><span>${esc(item.inputs.targetDate)}</span></header><p>${esc(item.inputs.weather.condition)} · ${item.inputs.route.minutes} 分钟 · ${esc(item.inputs.dayRule.label)}</p><small>${esc(item.evaluatedAt)} · ${esc(item.decision)}</small>${event('查看分解','select-evaluation-history',item.id)}</article>`; return `<section class="alarm-page alarm-history"><div class="alarm-history-filter">${event(label,'overlay','history-filter')}</div><section class="evaluation-history"><header><h2>自动评估决策</h2><span>离线 fixture</span></header>${decisions.map(decisionCard).join('')}</section>${events.length ? `<section class="local-event-history"><h2>本机闹钟事件</h2>${events.map(item => `<section class="alarm-history-day"><article class="${item.type === 'failed' ? 'is-failed' : ''}"><b>${esc(item.time || '—')}</b><em>${esc(({registered:'已注册',stopped:'已停止',snoozed:'已贪睡',failed:'异常'})[item.type] || item.type)}</em><p>${esc(item.message)}</p><small>${esc(item.date)}</small></article></section>`).join('')}</section>` : ''}<p class="alarm-history-note">决策只记录离线 fixture 的输入摘要和结果；地址、坐标与凭据不显示。</p></section>`; },
    why() { const run = assessment(); const schedule = run.schedule; const actionLabel = ({ create_early_reminder:'创建独立提前提醒', preserve_early_reminder:'保留已有提前提醒', none:'不创建提前提醒' })[schedule.action] || schedule.action; return `<section class="alarm-page evaluation-detail"><article class="evaluation-detail-hero is-${esc(run.state)}"><small>自动评估 · ${esc(run.evaluatedAt)}</small><h2>${esc(run.title)}</h2><p>${esc(run.detail)}</p></article><article class="alarm-breakdown"><header><h2>决策分解</h2><span>${esc(run.inputs.targetDate)}</span></header><div><span>路线</span><b>${esc(run.inputs.route.transport)} ${run.inputs.route.minutes} 分钟</b><small>${esc(run.inputs.route.source)}</small></div><div><span>天气</span><b>${esc(run.inputs.weather.condition)} +${run.inputs.weather.bufferMinutes} 分钟</b><small>${esc(run.inputs.weather.source)} · ${esc(run.inputs.weather.observedAt)}</small></div><div><span>日期规则</span><b>${esc(run.inputs.dayRule.label)}</b><small>${esc(run.inputs.dayRule.source)}</small></div><footer><span>基础闹钟 ${esc(schedule.baseWake)}</span><b>${schedule.earlyWake ? `提前提醒 ${esc(schedule.earlyWake)}` : actionLabel}</b></footer></article><article class="evaluation-safety"><b>调度动作</b><p>${esc(actionLabel)}。基础闹钟维持 ${esc(schedule.baseWake)}，提前提醒独立展示。</p></article>${link('查看决策记录', 'history','class="alarm-tonal-action"')}</section>`; },
    failure() { const run = assessment(); const retry = run.state === 'retry'; const unavailable = [EVALUATION_FIXTURE_STATES.RETRY, EVALUATION_FIXTURE_STATES.DEADLINE, EVALUATION_FIXTURE_STATES.EXPIRED].includes(run.state); return `<section class="alarm-page"><article class="alarm-failure-main"><h2>${esc(run.title)}</h2><p>${esc(run.detail)}</p>${retry ? `<strong>第 ${run.retryCount} 次失败 · 下次重试 ${esc(run.retryAt)}</strong>` : ''}</article>${unavailable ? `<article class="alarm-failure-clock"><h2>基础闹钟</h2><p><b>${esc(run.schedule.baseWake)}</b><em>保持原计划</em></p><span>不会根据失败、截止或过期结果新增提前提醒。</span></article>` : ''}<div class="alarm-failure-actions">${event('重新评估','evaluate-now')}${link('查看决策记录','history')}</div></section>`; },
    rest() { return '<section class="alarm-page"><article class="local-empty-state"><h2>天气缓冲暂未用于闹钟</h2><p>基础闹钟可继续创建；彩云天气 fixture 不会计算或应用提前时间。</p></article></section>'; },
    'overtime-select'() { return `<section class="alarm-page"><article class="local-empty-state"><h2>请在日历中设置单日覆盖</h2><p>单日覆盖仅作用于选中的闹钟和日期。</p></article>${footer(link('打开工作日日历','calendar'))}</section>`; },
    'overtime-active'() { return this.plans(); },
  };
}
