import { EVALUATION_FIXTURE_STATES, REPEAT_KINDS, createEvaluationFixture, repeatLabel } from './state.mjs';
import { fourWeekLegalCalendar } from './legal-calendar.mjs';
import { alarmCountdown } from './time-wheel.mjs';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const weekday = ['一','二','三','四','五','六','日'];

const workdayPreview = now => {
  const calendar = fourWeekLegalCalendar(now);
  return `<article class="workday-calendar" aria-label="工作日预览"><h2>工作日预览</h2><div class="workday-calendar-headings">${weekday.map(day => `<span>${day}</span>`).join('')}</div><div class="workday-calendar-weeks">${calendar.map(week => `<div class="workday-calendar-week">${week.days.map(day => `<span class="workday-calendar-day is-${day.kind} ${day.isToday ? 'is-today' : ''}" data-calendar-date="${day.date}">${day.day}</span>`).join('')}</div>`).join('')}</div></article>`;
};

export function createAlarmScreens({ action, overlayAction, asset, state, now = () => new Date() }) {
  const read = () => (typeof state === 'function' ? state() : state) || {};
  const link = (label, route, extra = '') => action(label, route, extra);
  const event = (label, name, value = '') => overlayAction(label, name, value);
  const icon = (file, alt = '') => asset(file, alt, 'alarm-icon');
  const current = () => { const snapshot = read(); const c = snapshot.config || snapshot; const r = snapshot.runtime || {}; return { c, r, plan:r.alarmDraft || c.alarmPlans?.find(item => item.id === r.editingAlarmId) }; };
  const assessment = () => { const { r } = current(); return r.evaluationRun || createEvaluationFixture({ fixture:r.evaluationFixture || EVALUATION_FIXTURE_STATES.PENDING, plan:r.evaluationPlan }); };
  const footer = content => `<footer class="screen-footer alarm-footer">${content}</footer>`;
  const status = plan => ({ pendingPermission:'待 Android 注册', registered:'已注册', failed:'注册失败', completed:'已完成' })[plan.scheduleStatus] || '待 Android 注册';
  return {
    plans() {
      const { c } = current(); const plans = c.alarmPlans || [];
      const card = plan => { const decisions = (current().r.evaluationHistory || []).filter(item => item.planId === plan.id); return `<article class="local-alarm-card ${plan.enabled ? '' : 'is-disabled'}"><header><button type="button" data-action="edit-alarm" data-value="${esc(plan.id)}"><b>${esc(plan.name || `${plan.time} 闹钟`)}</b><small>${esc(repeatLabel(plan))}</small></button><label class="alarm-switch"><input type="checkbox" data-action="toggle-alarm" data-value="${esc(plan.id)}" ${plan.enabled ? 'checked' : ''}><span></span></label></header><div><b>${esc(plan.time)}</b><p>${esc(status(plan))}<small>${plan.enabled ? '由 Android 本地闹钟服务处理' : '已停用'}</small></p></div>${decisions.length ? `<div class="alarm-decision-links"><small>相关决策</small>${decisions.map(item => event(`${item.inputs.targetDate} · ${item.title}`, 'open-decision', item.decisionId)).join('')}</div>` : ''}<footer><span>${plan.vibration ? '振动开启' : '振动关闭'} · 贪睡 ${plan.snoozeMinutes} 分钟</span>${event('编辑','edit-alarm',plan.id)}</footer></article>`; };
      return `<section class="alarm-page alarm-plans"><p class="alarm-page-note">高德通勤支持全局设置与计划覆盖。</p>${plans.length ? plans.map(card).join('') : `<article class="local-empty-state">${icon('2c52264e-dee6-4069-95c5-e8105043da04.svg')}<h2>还没有闹钟</h2><p>添加单次、每周或工作日闹钟。Android 将负责实际注册与响铃。</p></article>`}<button type="button" class="local-add-alarm" data-action="new-alarm">＋ 添加闹钟</button>${footer(link('查看本机记录','history','class="alarm-tonal-action"'))}</section>`;
    },
    'plan-edit'() {
      const { plan, r, c } = current(); if (!plan) return '<section class="alarm-page"><p>请选择一个闹钟。</p></section>';
      const repeat = plan.repeat || { kind:REPEAT_KINDS.ONCE }; const labels = { once:'指定日期', weekly:'每周重复', workdays:'法定工作日' };
      const schedule = `<article class="alarm-rule-list"><label class="local-field"><span>日期</span><input type="date" data-alarm-field="date" value="${esc(repeat.date || '')}" ${repeat.kind === REPEAT_KINDS.ONCE ? '' : 'disabled'}></label><div class="local-repeat-group">${Object.entries(labels).map(([key,label]) => `<button type="button" data-action="select-repeat" data-value="${key}" class="${repeat.kind === key ? 'is-selected' : ''}">${label}</button>`).join('')}</div>${repeat.kind === REPEAT_KINDS.WEEKLY ? `<div class="local-weekdays">${weekday.map((label,index) => `<button type="button" data-action="toggle-weekday" data-value="${index + 1}" class="${repeat.weekdays?.includes(index + 1) ? 'is-selected' : ''}">${label}</button>`).join('')}</div>` : ''}</article>`;
      const sound = `<article class="alarm-sound-list"><div class="alarm-row">${icon('1a089d58-bce2-4212-9ddf-707263a04ac1.svg')}<strong>铃声与振动</strong><span>${esc(plan.ringtone)} · ${plan.vibration ? '开启' : '关闭'}</span>${event('','overlay','alarm-sound')}</div><div class="alarm-row">${icon('129742a8-cb1d-4163-9258-71c82066766b.svg')}<strong>贪睡时长</strong><span>${plan.snoozeMinutes} 分钟</span>${event('','overlay','alarm-snooze')}</div><button type="button" class="alarm-row local-calendar-entry" data-action="open-calendar"><strong>单日覆盖</strong><span>仅本计划指定日期</span><i>›</i></button></article>`;
      const commuteDetails = r.commuteSettingsExpanded ? `<div class="alarm-commute-details"><div class="alarm-row"><strong>期望到达时间</strong><span>${esc(plan.arrivalTime)}</span>${event('','overlay','arrival-time')}</div><div class="alarm-row"><strong>准备时间</strong><span>${plan.preparationMinutes} 分钟</span>${event('','overlay','preparation-minutes')}</div><div class="alarm-row"><strong>最多提前</strong><span>${plan.maxAdvanceMinutes} 分钟</span>${event('','overlay','max-advance-minutes')}</div><div class="alarm-commute-route"><div><strong>通勤路线</strong><span>${plan.commuteOverride?.enabled ? '本计划覆盖' : '使用全局通勤'}</span></div><button type="button" data-action="edit-plan-commute">编辑本计划覆盖</button>${plan.commuteOverride?.enabled ? '<button type="button" data-action="use-global-commute">恢复全局通勤</button>' : ''}</div></div>` : '';
      const commute = `<article class="alarm-commute-settings ${r.commuteSettingsExpanded ? 'is-expanded' : ''}"><button type="button" class="alarm-commute-summary" data-action="toggle-commute-settings" aria-expanded="${Boolean(r.commuteSettingsExpanded)}"><span><strong>通勤与提前提醒</strong><small>${plan.commuteOverride?.enabled ? '本计划通勤已覆盖' : '使用全局通勤；可按需设置提前提醒'}</small></span><i>${r.commuteSettingsExpanded ? '收起' : '设置'}</i></button>${commuteDetails}</article>`;
      return `<section class="alarm-page alarm-plan-edit local-alarm-editor"><article class="alarm-baseline-card"><div><small>响铃时间</small><em>${esc(status(plan))}</em></div><b>${esc(plan.time)}</b>${event('编辑时间','overlay','alarm-time')}<p data-alarm-countdown>${esc(alarmCountdown(plan, now(), c.dateOverrides))}</p></article>${schedule}${repeat.kind === REPEAT_KINDS.WORKDAYS ? workdayPreview(now()) : ''}${sound}${commute}<label class="alarm-note-card"><span>备注（可选）</span><input data-alarm-field="name" value="${esc(plan.name)}" maxlength="100" placeholder="输入备注" aria-label="备注"></label><button type="button" class="local-delete" data-action="delete-alarm" data-value="${esc(plan.id)}">删除闹钟</button>${footer(event('保存闹钟','save-alarm'))}</section>`;
    },
    history() { const { c, r } = current(); const events = (c.alarmEvents || []).filter(item => r.historyFilter === 'all' || !r.historyFilter || item.type === r.historyFilter); const label = ({all:'全部',registered:'已注册',stopped:'已停止',snoozed:'已贪睡',failed:'异常'})[r.historyFilter || 'all']; const decisions = r.evaluationHistory || []; const decisionCard = item => { const inputs = item.inputs || {}; const weather = inputs.weather || {}; const route = inputs.route || {}; return `<article class="evaluation-history-card is-${esc(item.state)}"><header><b>${esc(item.title || '本次未提供')}</b><span>${esc(inputs.targetDate || '本次未提供')}</span></header><p>${esc(item.planSnapshot?.name || '本次未提供')} · ${esc(weather.condition || '本次未提供')} · ${esc(route.minutes ?? '本次未提供')} 分钟</p><small>${esc(item.evaluatedAt || '本次未提供')} · ${esc(item.decisionId || '本次未提供')}</small>${item.decisionId ? event('查看详情','open-decision',item.decisionId) : ''}</article>`; }; return `<section class="alarm-page alarm-history"><div class="alarm-history-filter">${event(label,'overlay','history-filter')}</div><section class="evaluation-history"><header><h2>自动评估决策</h2><span>离线 fixture</span></header>${decisions.length ? decisions.map(decisionCard).join('') : '<article class="local-empty-state"><h2>暂无本次决策</h2><p>无法根据当前计划或天气补填历史记录。</p></article>'}</section>${events.length ? `<section class="local-event-history"><h2>本机闹钟事件</h2>${events.map(item => `<section class="alarm-history-day"><article class="${item.type === 'failed' ? 'is-failed' : ''}"><b>${esc(item.time || '—')}</b><em>${esc(({registered:'已注册',stopped:'已停止',snoozed:'已贪睡',failed:'异常'})[item.type] || item.type)}</em><p>${esc(item.message)}</p><small>${esc(item.date)}</small></article></section>`).join('')}</section>` : ''}<p class="alarm-history-note">决策只记录离线 fixture 的输入摘要和结果；地址、坐标与凭据不显示。</p></section>`; },
    why() { const { r } = current(); const run = r.selectedDecision; if (!run) return `<section class="alarm-page evaluation-detail"><article class="local-empty-state"><h2>本次决策不可用</h2><p>未找到该实例关联的决策记录；不会改为展示其他记录。</p></article>${link('查看决策记录', 'history','class="alarm-tonal-action"')}</section>`; const inputs = run.inputs || {}; const schedule = run.schedule || {}; const route = inputs.route || {}; const weather = inputs.weather || {}; const dayRule = inputs.dayRule || {}; const actionLabel = ({ create_early_reminder:'已申请独立提前提醒', preserve_early_reminder:'保留已有提前提醒', none:'未创建提前提醒' })[schedule.action] || '本次未提供'; const actual = schedule.actualWake ? `实际注册 ${schedule.actualWake}` : run.applicationOutcome === 'not_needed' ? '无需注册提前提醒' : '本次未提供'; const occurrenceState = ({ RINGING:'响铃中', SNOOZED:'已贪睡', STOPPED:'已停止', SCHEDULED:'已注册' })[run.occurrence?.state] || '本次未提供'; const instance = run.occurrence ? `${run.occurrence.kind === 'ADVANCE' ? '提前实例' : '实例'} · ${occurrenceState}` : '本次未提供'; return `<section class="alarm-page evaluation-detail"><article class="evaluation-detail-hero is-${esc(run.state)}"><small>${esc(run.planSnapshot?.name || '本次未提供')} · 目标 ${esc(inputs.targetDate || '本次未提供')}</small><h2>${esc(run.title || '本次未提供')}</h2><p>${esc(run.detail || '本次未提供')}</p></article><article class="evaluation-result-card"><span>评估结果</span><b>基础 ${esc(schedule.baseWake || '本次未提供')}</b><strong>${schedule.earlyWake ? `建议 ${esc(schedule.earlyWake)}` : '无需提前'}</strong></article><article class="evaluation-result-card"><span>调度应用结果</span><b>${esc(actionLabel)}</b><strong>${esc(actual)}</strong></article><article class="evaluation-result-card"><span>实例当前状态</span><b>${esc(instance)}</b><strong>${r.selectedOccurrenceId ? `当前实例 ${esc(r.selectedOccurrenceId)}` : '本次未提供'}</strong></article><article class="alarm-breakdown"><header><h2>本次决策分解</h2><span>${esc(run.evaluatedAt || '本次未提供')}</span></header><div><span>出发</span><b>预计 ${esc(inputs.estimatedDepartureTime || '本次未提供')} 出发</b><small>通勤 ${esc(route.minutes ?? '本次未提供')} 分钟 · 准备 ${esc(inputs.preparationMinutes ?? '本次未提供')} 分钟</small></div><div><span>天气</span><b>${esc(weather.condition || '本次未提供')} +${esc(weather.bufferMinutes ?? '本次未提供')} 分钟</b><details class="evaluation-source-details"><summary>数据来源与更新时间</summary><small>${esc(weather.source || '本次未提供')} · ${esc(weather.observedAt || '本次未提供')}</small></details></div><div><span>日期</span><b>${esc(dayRule.label || '本次未提供')}</b><details class="evaluation-source-details"><summary>日期规则来源</summary><small>${esc(dayRule.source || '本次未提供')}</small></details></div><footer><span>计划修订 ${esc(run.planRevision || '本次未提供')}</span><b>${esc(run.expiresAt || '本次未提供')}</b></footer></article>${link('查看决策记录', 'history','class="alarm-tonal-action"')}</section>`; },
    failure() { const { r } = current(); const run = r.selectedDecision; if (!run) return `<section class="alarm-page"><article class="local-empty-state"><h2>本次评估记录不可用</h2><p>未找到对应决策；无法据此推断注册结果。</p></article>${link('查看决策记录','history')}</section>`; const inputs = run.inputs || {}; const retry = Boolean(run.retryAt); const impact = ({ preserved_existing:'已保留既有提前提醒', registration_failed:'提前提醒未注册，基础闹钟保持原计划', limited_by_maximum:`实际最多提前 ${run.schedule?.actualWake || '本次未提供'}`, skipped:'基础闹钟保持原计划', historical_only:'仅保留历史结果' })[run.applicationOutcome] || '本次未提供'; return `<section class="alarm-page"><article class="alarm-failure-main"><small>${esc(run.planSnapshot?.name || '本次未提供')} · ${esc(inputs.targetDate || '本次未提供')}</small><h2>${esc(run.title || '本次未提供')}</h2><p>${esc(run.failureReason || run.detail || '本次未提供')}</p>${retry ? `<strong>第 ${run.attemptNumber || run.retryCount || '本次未提供'} 次尝试 · 下次重试 ${esc(run.retryAt)}</strong>` : ''}</article><article class="alarm-failure-clock"><h2>对本次闹钟的影响</h2><p><b>${esc(run.schedule?.baseWake || '本次未提供')}</b><em>${esc(impact)}</em></p><span>${esc(run.fallbackReason || '本次未提供')}</span></article><div class="alarm-failure-actions">${event('重新评估','re-evaluate-decision')}${link('检查凭据','credentials')}</div><div class="alarm-failure-actions">${link('可靠性诊断','diagnostics')}${link('查看决策记录','history')}</div></section>`; },
    rest() { return '<section class="alarm-page"><article class="local-empty-state"><h2>天气缓冲暂未用于闹钟</h2><p>基础闹钟可继续创建；彩云天气 fixture 不会计算或应用提前时间。</p></article></section>'; },
    'overtime-select'() { return `<section class="alarm-page"><article class="local-empty-state"><h2>请在日历中设置单日覆盖</h2><p>单日覆盖仅作用于选中的闹钟和日期。</p></article>${footer(link('打开工作日日历','calendar'))}</section>`; },
    'overtime-active'() { return this.plans(); },
  };
}
