import { REPEAT_KINDS, repeatLabel } from './state.mjs';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const weekday = ['一','二','三','四','五','六','日'];

export function createAlarmScreens({ action, overlayAction, asset, state }) {
  const read = () => (typeof state === 'function' ? state() : state) || {};
  const link = (label, route, extra = '') => action(label, route, extra);
  const event = (label, name, value = '') => overlayAction(label, name, value);
  const icon = (file, alt = '') => asset(file, alt, 'alarm-icon');
  const current = () => { const snapshot = read(); const c = snapshot.config || snapshot; const r = snapshot.runtime || {}; return { c, r, plan:r.alarmDraft || c.alarmPlans?.find(item => item.id === r.editingAlarmId) }; };
  const footer = content => `<footer class="screen-footer alarm-footer">${content}</footer>`;
  const status = plan => ({ pendingPermission:'待 Android 注册', registered:'已注册', failed:'注册失败', completed:'已完成' })[plan.scheduleStatus] || '待 Android 注册';
  return {
    plans() {
      const { c } = current(); const plans = c.alarmPlans || [];
      const card = plan => `<article class="local-alarm-card ${plan.enabled ? '' : 'is-disabled'}"><header><button type="button" data-action="edit-alarm" data-value="${esc(plan.id)}"><b>${esc(plan.name)}</b><small>${esc(repeatLabel(plan))}</small></button><label class="alarm-switch"><input type="checkbox" data-action="toggle-alarm" data-value="${esc(plan.id)}" ${plan.enabled ? 'checked' : ''}><span></span></label></header><div><b>${esc(plan.time)}</b><p>${esc(status(plan))}<small>${plan.enabled ? '由 Android 本地闹钟服务处理' : '已停用'}</small></p></div><footer><span>${plan.vibration ? '振动开启' : '振动关闭'} · 贪睡 ${plan.snoozeMinutes} 分钟</span>${event('编辑','edit-alarm',plan.id)}</footer></article>`;
      return `<section class="alarm-page alarm-plans"><p class="alarm-page-note">高德通勤支持全局设置与计划覆盖。</p>${plans.length ? plans.map(card).join('') : `<article class="local-empty-state">${icon('2c52264e-dee6-4069-95c5-e8105043da04.svg')}<h2>还没有闹钟</h2><p>添加单次、每周或工作日闹钟。Android 将负责实际注册与响铃。</p></article>`}<button type="button" class="local-add-alarm" data-action="new-alarm">＋ 添加闹钟</button>${footer(link('查看本机记录','history','class="alarm-tonal-action"'))}</section>`;
    },
    'plan-edit'() {
      const { plan } = current(); if (!plan) return '<section class="alarm-page"><p>请选择一个闹钟。</p></section>';
      const repeat = plan.repeat || { kind:REPEAT_KINDS.ONCE }; const labels = { once:'指定日期', weekly:'每周重复', workdays:'工作日' };
      return `<section class="alarm-page alarm-plan-edit local-alarm-editor"><article class="alarm-baseline-card"><div><small>闹钟名称</small><em>${esc(status(plan))}</em></div><input class="local-name-input" data-alarm-field="name" value="${esc(plan.name)}" maxlength="24" aria-label="闹钟名称"><b>${esc(plan.time)}</b>${event('编辑时间','overlay','alarm-time')}</article><article class="alarm-rule-list"><label class="local-field"><span>日期与时间</span><input type="date" data-alarm-field="date" value="${esc(repeat.date || '')}" ${repeat.kind === REPEAT_KINDS.ONCE ? '' : 'disabled'}><input type="time" data-alarm-field="time" value="${esc(plan.time)}"></label><div class="local-repeat-group">${Object.entries(labels).map(([key,label]) => `<button type="button" data-action="select-repeat" data-value="${key}" class="${repeat.kind === key ? 'is-selected' : ''}">${label}</button>`).join('')}</div>${repeat.kind === REPEAT_KINDS.WEEKLY ? `<div class="local-weekdays">${weekday.map((label,index) => `<button type="button" data-action="toggle-weekday" data-value="${index + 1}" class="${repeat.weekdays?.includes(index + 1) ? 'is-selected' : ''}">${label}</button>`).join('')}</div>` : ''}</article><article class="alarm-sound-list"><div class="alarm-row">${icon('1a089d58-bce2-4212-9ddf-707263a04ac1.svg')}<strong>铃声与振动</strong><span>${esc(plan.ringtone)} · ${plan.vibration ? '开启' : '关闭'}</span>${event('','overlay','alarm-sound')}</div><div class="alarm-row">${icon('129742a8-cb1d-4163-9258-71c82066766b.svg')}<strong>贪睡时长</strong><span>${plan.snoozeMinutes} 分钟</span>${event('','overlay','alarm-snooze')}</div><button type="button" class="alarm-row local-calendar-entry" data-action="open-calendar"><strong>单日覆盖</strong><span>仅本计划指定日期</span><i>›</i></button></article><article class="alarm-sound-list amap-plan-commute"><div><strong>通勤路线</strong><span>${plan.commuteOverride?.enabled ? '本计划覆盖' : '使用全局通勤'}</span></div><button type="button" data-action="edit-plan-commute">编辑本计划覆盖</button>${plan.commuteOverride?.enabled ? '<button type="button" data-action="use-global-commute">恢复全局通勤</button>' : ''}</article><button type="button" class="local-delete" data-action="delete-alarm" data-value="${esc(plan.id)}">删除闹钟</button>${footer(event('保存闹钟','save-alarm'))}</section>`;
    },
    history() { const { c, r } = current(); const events = (c.alarmEvents || []).filter(item => r.historyFilter === 'all' || !r.historyFilter || item.type === r.historyFilter); const label = ({all:'全部',registered:'已注册',stopped:'已停止',snoozed:'已贪睡',failed:'异常'})[r.historyFilter || 'all']; return `<section class="alarm-page alarm-history"><div class="alarm-history-filter">${event(label,'overlay','history-filter')}</div>${events.length ? events.map(item => `<section class="alarm-history-day"><article class="${item.type === 'failed' ? 'is-failed' : ''}"><b>${esc(item.time || '—')}</b><em>${esc(({registered:'已注册',stopped:'已停止',snoozed:'已贪睡',failed:'异常'})[item.type] || item.type)}</em><p>${esc(item.message)}</p><small>${esc(item.date)}</small></article></section>`).join('') : '<article class="local-empty-state"><h2>暂无本机记录</h2><p>注册、触发、停止、贪睡和异常事件会显示在这里。</p></article>'}<p class="alarm-history-note">记录仅展示本机闹钟事件，不包含地址、天气或地图数据。</p></section>`; },
    why() { return '<section class="alarm-page"><article class="local-empty-state"><h2>提前计算暂未接入</h2><p>天气服务仍待接入。</p></article></section>'; },
    failure() { return '<section class="alarm-page"><article class="alarm-failure-main"><h2>没有可展示的天气计算结果</h2><p>天气服务暂未接入。</p></article></section>'; },
    rest() { return '<section class="alarm-page"><article class="local-empty-state"><h2>天气缓冲暂未接入</h2><p>基础闹钟可继续创建。天气缓冲将在天气服务接入后开放。</p></article></section>'; },
    'overtime-select'() { return `<section class="alarm-page"><article class="local-empty-state"><h2>请在日历中设置单日覆盖</h2><p>单日覆盖仅作用于选中的闹钟和日期。</p></article>${footer(link('打开工作日日历','calendar'))}</section>`; },
    'overtime-active'() { return this.plans(); },
  };
}
